### ISSUE TITLE
Higher contrast links

### ISSUE THREAD

**Issue by marisademeglio** [IDPF/epubtestweb#29]
Link colors are not AAA. Luminosity Contrast Ratio for #2a6496 and #FFFFFF is 6.25:1 (Threshold: greater than 7:1 for AAA, 4.5:1 for AA).

**Comment by paigepoe** [comment]
#2a6496 is bootstrap.css default link color style — don't think we're actually using it.

**Comment by marisademeglio** [comment]
I think it's used for a.hover and a.focus (see screenshot). And if we look at the luminosity contrast ratio for the usual link colors (#0099cc vs #fff), it's only 3.27:1 (via http://juicystudio.com/services/luminositycontrastratio.php).
![screen shot 2015-04-02 at 11 38 43 am](https://cloud.githubusercontent.com/assets/734730/6970933/af42ec7a-d92d-11e4-9cfb-691a5b224343.png)

**Comment by marisademeglio** [comment]
Fixed in 28c37484c81ec0e21d0118bb5717a9d0d1debd75
