### ISSUE TITLE
When epubtest.org: results is first displayed, the rows should be sorted alphabetically by test environment

### ISSUE THREAD

**Issue by ways2read** [IDPF/epubtestweb#73]
Furthermore, it would be nice to sort the rows by the values in other columns.

**Comment by marisademeglio** [comment]
For me, the rows are sorted by testing environment initially, and you can click on the column headers to sort them. What are you seeing instead?

**Comment by ways2read** [comment]
The first three I have listed when I first open the results page are: Dolphin Easyreader, Microsoft Edge, Adobe Digital Editions

**Comment by ways2read** [comment]
After some experimentation, we find that sorting by column headings works in Firefox, but not in Chrome, Edge or Edge developer channel (Chromium based public beta).

**Comment by marisademeglio** [comment]
Fixed
